spring:
  application:
    name: todo-ai-app
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/todoai}
    username: ${DATABASE_USERNAME:todoai}
    password: ${DATABASE_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
  security:
    jwt:
      secret: ${JWT_SECRET:defaultSecret}
      expiration: ${JWT_EXPIRATION:86400000}

openai:
  api:
    key: ${OPENAI_API_KEY:your-openai-api-key}

server:
  port: ${PORT:8080}

logging:
  level:
    com.todoai: INFO
    org.springframework.security: WARN
    org.springframework.web: WARN
    org.hibernate: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
