spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: ${DB_MAX_POOL_SIZE:10}  # Maximum number of connections in the pool
      minimum-idle: 2            # Minimum idle connections
      idle-timeout: 30000        # Time in ms before an idle connection is removed
      connection-timeout: 30000  # Max time in ms to wait for a connection
      max-lifetime: 1800000

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
  security:
    jwt:
      secret: ${JWT_SECRET:defaultSecret}
      expiration: ${JWT_EXPIRATION:86400000}

openai:
  api:
    key: ${OPENAI_API_KEY:your-openai-api-key}

server:
  port: ${PORT:8080}

logging:
  level:
    com.todoai: INFO
    org.springframework.security: WARN
    org.springframework.web: WARN
    org.hibernate: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
