spring:
  datasource:
    # Use environment variables for database connection
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/todoai_dev}
    username: ${DATABASE_USERNAME:dev_user}
    password: ${DATABASE_PASSWORD:dev_password}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 6
      minimum-idle: 2
      idle-timeout: 30000
      connection-timeout: 30000
      max-lifetime: 1800000

  jpa:
    hibernate:
      ddl-auto: update  # Changed from 'none' to allow schema updates
    show-sql: false  # Disabled for production
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect


openai:
  api:
    key: ${OPENAI_API_KEY:your-openai-api-key}

jwt:
  secret: ${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970337336763979244226452948404D635166546A576E5A7234753778214125442A}

logging:
  level:
    org.hibernate.SQL: WARN
    org.hibernate.orm.sql.ast: WARN
    org.hibernate.orm.results.graph: WARN
    org.hibernate.internal.AbstractSharedSessionContract: ERROR