spring:
  profiles:
    active: production

  jpa:
    hibernate:
      ddl-auto: validate  # Most secure for production
    show-sql: false
    properties:
      hibernate:
        format_sql: false

logging:
  level:
    com.todoai: INFO
    org.springframework.security: WARN
    org.hibernate: WARN
    org.springframework.web: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
